### ISSUE TITLE
Hardcoded to LOD mod, making it useless for other mods

### ISSUE THREAD

**Issue by CodeF53** [Ran-helo/DHJarMerger#4]
https://github.com/Ran-helo/DHJarMerger/blob/2b5806cf088a91f91b57e889353d8d07d26d3884/src/main/java/io/github/ran/jarmerger/MergeJarsTask.java#L91

**Comment by Ran-Mewo** [comment]
Use [Forgix](https://github.com/PacifistMC/Forgix) instead
